### ISSUE TITLE
vg::textBox() broken

### ISSUE THREAD

**Issue by hugoam** [jdryg/vg-renderer#13]
`vg::textBox()` implementation doesn't match it's declaration anymore so you get link error if you use that function.
Quickest fix I is changing the declaration in `vg.h` to (also defaulted to not break the API, but who cares :) ) :
```
void textBox(Context* ctx, const TextConfig& cfg, float x, float y, float breakWidth, const char* text, const char* end, uint32_t flags = 0U);
```

**Comment by jdryg** [comment]
Should be fixed. I don't use those functions in my project that's why I missed it for so long (only use clXXX functions).
Thanks!
