### ISSUE TITLE
vg::roundedRect can glitch when corner radius == half height

### ISSUE THREAD

**Issue by simsaens** [jdryg/vg-renderer#38]
When using `vg::roundedRect` with a corner radius that is half the height (or width) of the rectangle, the resulting shape will render with incorrect joins

![image](https://github.com/user-attachments/assets/e075a3bc-fea7-4ef9-ad66-fe9db2ba2056)

In this case the height is `80` and the corner radius is set to `40`

This appears to be a regression that was not present in earlier versions of vg-renderer. I have tracked this down to this removed code:

![image](https://github.com/user-attachments/assets/04c8d331-4a36-4169-9884-efd856ca13b1)

If I re-enable the disabled block of code then the rendering of this pill shaped object is correct:

![image](https://github.com/user-attachments/assets/4335755d-a97d-494e-8382-696258028ae0)

**Comment by jdryg** [comment]
Thanks for the bug report. Unfortunately, I don't remember why I added the #if 0 around that block. The code should be always executed because the stroker cannot handle degenerate line segments.
