### ISSUE TITLE
Doesn't compile on gcc and clang

### ISSUE THREAD

**Issue by hugoam** [jdryg/vg-renderer#6]
There are a bunch of compile errors when trying to compile with gcc or clang :
https://gist.github.com/hugoam/fe72597497fea5501588e633de030066
Basically the problems are :
- `<fontstash.h>` needs `<limits.h>` and `<math.h>` to be included before it's included or else `INT_MAX` and `expf` are undefined
- the functions `addPos`, `addIndices` and `addPosColor` in `stroker.cpp` need to be defined before they are used (they aren't)

**Comment by jdryg** [comment]
Thanks! I haven't had the chance to try it with gcc/clang yet, that's why I missed those. Should be fixed in the cmdlists branch, which I assume is the branch you are using (right?).

**Comment by jdryg** [comment]
cmdlists branch merged to master. I'm keeping this open until I manage to properly test it on gcc/clang on my own. If anything else regarding compile/link errors comes up, feel free to post it here.

**Comment by jdryg** [comment]
Fixed! It was a leftover from my external SIMD tests. For some reason MSVC didn't complain which I guess means that cmath/math.h was included somewhere.

**Comment by hugoam** [comment]
Thanks ! 
Also this is just a warning but you might want to fix it since it's in the header : 
```
../../../mud/3rdparty/vg-renderer/include/vg/vg.h:82:40: warning: missing initializer for member ‘vg::GradientHandle::flags’ [-Wmissing-field-initializers]
 #define VG_INVALID_HANDLE { UINT16_MAX }
                                        ^
../../../mud/3rdparty/vg-renderer/src/vg.cpp:3437:10: note: in expansion of macro ‘VG_INVALID_HANDLE’
   return VG_INVALID_HANDLE;
```

**Comment by jdryg** [comment]
Fixed.

**Comment by hugoam** [comment]
Cool !
Now I'm trying to build with Emscripten right now which I guess went out of sync : 
this line : https://github.com/jdryg/vg-renderer/blob/master/src/vg.cpp#L2190
needs to be : 
```
	if (!bx::isPowerOf2(w) || !bx::isPowerOf2(h)) {
```
and this line : https://github.com/jdryg/vg-renderer/blob/master/src/vg.cpp#L1036
needs to be enclosed in a `BX_CONFIG_SUPPORTS_THREADING` guard
```
#if BX_CONFIG_SUPPORTS_THREADING
	BX_DELETE(allocator, ctx->m_DataPoolMutex);
#endif
```
